name: Upload Static Website

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set AWS IAM credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: 'ap-southeast-2'
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - name: copy to S3
      run: aws s3 sync . s3://chandan-static-website --exclude '.git*/*'

